### ISSUE TITLE
Improve docs around config options for functions

### ISSUE THREAD

**Issue by raksiv** [nitrictech/docs#366]
We've added functionality for adding config settings to functions - 

Add or improve the docs on what these config options are , with examples.

**Comment by raksiv** [comment]
@asalkeld  can you tell me if this is the full list of configuration options against a stack?

name: staging
provider: gcp
region: australia-southeast1
project: thing
**config:
  default:
    memory: 512
  functions/api/main.go:
    timeout: 30**

**Comment by HomelessDinosaur** [comment]
// The memory of the compute instance in MB: default 128
memory

// The minimum number of instances to keep alive: default 0
minScale

// The maximum number of instances to scale to: default 10
maxScale

// The max running time of the function: default 15
timeout

// Telemetry sampling percentage
telemetry

**Comment by asalkeld** [comment]
Hi @raksiv , as @HomelessDinosaur says there is also telemetry now (0-100 a percentage)

```yaml
name: staging
provider: gcp
region: australia-southeast1
project: thing
config:
  default:
    memory: 512
    telemetry: 10
  functions/api/main.go:
    timeout: 30
``
