### ISSUE TITLE
Secrets Plugins Configuration

### ISSUE THREAD

**Issue by raksiv** [nitrictech/docs#61]
Following the steps in the secrets page results with the following run-time error when attempting to use the secrets

`Secret plugin not registered`

Observed in Local nitric run.
Steps should be added to instruct users on how to register the Secrets plugin.

**Comment by jyecusch** [comment]
@raksiv can you run `docker pull nitricimages/membrane-local` and try this again? I can't reproduce the issue currently.

**Comment by raksiv** [comment]
Issue no longer present in latest version, closing.
