### ISSUE TITLE
Single left nav for all pages

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/docs#611]
The current docs navigation includes sub-menus for most links in the left nav. Clicking the links changes the nav menu to display the sub-menu items. The intention was to avoid an overwhelming number of left nav links - but it's resulted in navigation that required more clicks and can be confusing, since the context constantly changes.

We want to redesign the left navigation to be a single list - an example of a site that does this well is [clerk.com](https://clerk.com/docs). We want to achieve something simiar - all links in one nav, with appropriate grouping and collapse/expand for more pages in sub-sections.

**Comment by davemooreuws** [comment]
Released
